#!/bin/sh
set -e

preprocess() {
    sway_config="${HOME}/.config/sway/config"
    unprocessed="${sway_config}.in"
    if ! test -e "$unprocessed"; then
        echo "Unprocessed config ${unprocessed} does not exist, \
exiting before overwriting $sway_config with nothing"
        exit 1
    fi
    # theoretically m4 -P is not POSIX, but freebsd m4 seems to have that option
    # so just hope I'll never use openbsd
    echo "# DON'T EDIT ME I'M AUTOGENERATED" > "$sway_config"
    m4 -P -DHOSTNAME="$(hostname)" -- "$unprocessed" >> "$sway_config"
}

usage() {
    echo "swaygen: helper script to use m4 macros with sway config"
    echo "Usage: swaygen [reload|start]"
    echo "Passed variables to m4 are: HOSTNAME(system hostname)"
    exit 1
}

if test -z "$1"; then
    usage
fi

case "$1" in
start)
    preprocess
    exec sway
;;
reload)
    preprocess
    swaymsg reload
;;
*)
    echo "Unknown cmd: $1"
    usage
;;
esac
